apiVersion: v1
kind: ServiceAccount
metadata:
  name: wto
  namespace: wto-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wto
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["workload-tuning.io"]
  resources: ["workloadprofiletemplates"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["workload-tuning.io"]
  resources: ["workloadprofiletemplates/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["workload-tuning.io"]
  resources: ["workloadprofiles"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["workload-tuning.io"]
  resources: ["workloadprofiles/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["workload-tuning.io"]
  resources: ["workloadprofiles/finalizers"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaimtemplates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["resource.k8s.io"]
  resources: ["deviceclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wto
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wto
subjects:
- kind: ServiceAccount
  name: wto
  namespace: wto-system
