apiVersion: workload-template.io/v1alpha1
kind: WorkloadTypeConfig
metadata:
  name: pytorchjob
  labels:
    workload-template.io/managed-by: wto-defaults
spec:
  group: kubeflow.org
  version: v1
  kind: PyTorchJob
  resource: pytorchjobs
  podTemplatePath: "spec.pytorchReplicaSpecs.Worker.template"
  knownContainerNames:
    - pytorch
  nativePropagation: false
